sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

php:
    - 5.6
    - 7.0

script:
    - ls -la

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=0

  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/wp-view-login-only/
    - GH_REF: https://github.com/chiilog/wp-view-login-only.git

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
